routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ViewController@index')->name('view.home');
Route::get('/all/products','ViewController@allproducts')->name('view.allproducts');
Route::post('/search/products','ViewController@searchproducts')->name('view.searchproducts');
Route::get('/category/{id}','ViewController@sub_subcategoryproduct')->name('view.sub_subcategoryproduct');
Route::get('/manufacturer/{id}','ViewController@manufacturerproduct')->name('view.manufacturerproduct');
Route::post('/product/price/range','ViewController@sortbypricerange')->name('view.sortbypricerange');
Route::get('/product/sort/by/price/low','ViewController@sortbypricelow')->name('view.sortbypricelow');
Route::get('/product/sort/by/price/high','ViewController@sortbypricehigh')->name('view.sortbypricehigh');
Route::get('/product/sort/by/name','ViewController@sortbyname')->name('view.sortbyname');
Route::get('/product/cart/add/{id}','ViewController@addtocart')->name('view.addtocart');
Route::post('/product/cart/add','ViewController@addtocartwithquantity')->name('view.addtocart');
Route::delete('/product/cart/remove', 'ViewController@remove');
Route::get('/product/{id}', 'ViewController@viewproduct')->name('view.product');
Route::get('/product/category/{id}', 'ViewController@categoryproduct')->name('view.categoryproduct');
Route::get('/cart', 'ViewController@viewcart')->name('view.cart');
Route::patch('/cart/update', 'ViewController@cartupdate');

Route::get('/customer/login','ViewController@loginview')->name('view.loginview');
Route::post('/customer/login','ViewController@login')->name('view.login');
Route::post('/customer/register','ViewController@register')->name('view.register');
Route::get('/customer/logout','ViewController@logout_customer')->name('view.logout');

Route::group(['middleware' => ['checkcustomersession']], function () {
    Route::get('/checkout', 'ViewController@viewcheckout')->name('view.checkout');
    Route::post('/order', 'OrderController@store')->name('order.store');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin',function(){
        return view('backend.dashboard');
    })->name('admin.home');

    Route::resource('/manufacturers', 'ManufacturerController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/subcategories', 'SubcategoryController');
    Route::resource('/products', 'ProductController');
    Route::resource('/sub_subcategories', 'Sub_subcategoryController');
    Route::get('/find/subcategories/{id}', 'Sub_subcategoryController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/subcategories/{id}', 'ProductController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/sub_subcategories/{id}', 'ProductController@findsubsubcategories')->name('find.subsubcategories');

    Route::get('/products/order/manage','OrderController@manageOrder')->name('manage.order');
    Route::get('/products/order/view/{id}','OrderController@viewOrderDetail')->name('view.order');
    Route::get('/products/delete/order/{id}','OrderController@deleteOrder')->name('delete.order');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Manufacturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    protected $fillable = [
        'title'
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/ManufacturerController.php
<?php

namespace App\Http\Controllers;

use App\Manufacturer;
use Illuminate\Http\Request;
use Session;

class ManufacturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $manufacturers=Manufacturer::all();

        return view('backend.manufacturers.index',compact('manufacturers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.manufacturers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->except('_token');

        Manufacturer::create($data);
        Session::flash('message','Created successfully');
        return redirect(route('manufacturers.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // dd($id);
        $manufacturer=Manufacturer::findOrFail($id);

        return view('backend.manufacturers.edit',compact('manufacturer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $manufacturer=Manufacturer::findOrfail($id);
        $data=$request->all();
        $manufacturer->update($data);
        Session::flash('message','Updated successfully');
        return redirect(route('manufacturers.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $manufacturer=Manufacturer::findOrfail($id);
        $manufacturer->delete();
        Session::flash('message','Deleted successfully');
        return redirect(route('manufacturers.index'));

    }
}

resources/views/backend/manufacturers/create.blade.php
@extends('backend.layouts.master')


@section('content')
<div class="page-inner no-page-title">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-title">
                            Create manufacturer
                        </div>    
                        <div class="panel-body">
                            <div class="row">
                                <center>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                    <form class="form-horizontal" action="{{ route('manufacturers.store') }}" method="post">
                                    @csrf    
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="title" id="inputEmail3" placeholder="Enter Manufacturer Title ....">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success horizontal-form-button">Create</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-md-2"></div>
                                </center>
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->
    </div><!-- /Page Inner -->

@endsection

resources/views/backend/manufacturers/edit.blade.php
@extends('backend.layouts.master')


@section('content')
<div class="page-inner no-page-title">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-title">
                            Update manufacturer
                        </div>    
                        <div class="panel-body">
                            <div class="row">
                                <center>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                    <form class="form-horizontal" action="{{ route('manufacturers.update',$manufacturer->id) }}" method="post">
                                    @csrf    
                                            <input name="_method" type="hidden" value="PUT">
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="title" id="inputEmail3" value="{{ $manufacturer->title }}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success horizontal-form-button">Update</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-md-2"></div>
                                </center>
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->
    </div><!-- /Page Inner -->

@endsection

resources/views/backend/manufacturers/index.blade.php
@extends('backend.layouts.master')
@section('css')
    <link href="{{asset('ui/backend/plugins/datatables/css/jquery.datatables.min.css')}}" rel="stylesheet">
    <link href="{{asset('ui/backend/plugins/datatables/css/jquery.datatables_themeroller.css')}}" rel="stylesheet">
@endsection

@section('content')
<div class="page-inner">

        <div class="page-title">
            <h3 class="breadcrumb-header">Manufacturers</h3>
        </div>
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-body">
                            @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                            @endif
                            <div class="table-responsive">
                                    <table id="example" class="display table table-data-width">
                                            <thead>
                                                <tr>
                                                    <th>Title</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                    <th>Title</th>
                                                    <th>Action</th>
                                                </tr>
                                            </tfoot>
                                            <tbody>
                                                @foreach ($manufacturers as $manufacturer)
                                                    <tr>
                                                        <td>{{ $manufacturer->title }}</td>
                                                        <td>
                                                        <form action="{{ route('manufacturers.destroy',$manufacturer->id) }}" method="POST"> 
                                                        @csrf
                                                        <a href="{{ route('manufacturers.edit',$manufacturer->id) }}" type="button" class="btn btn-info btn-rounded">Update</a>
                                                        <input name="_method" type="hidden" value="DELETE">
                                                            <button type="submit" class="btn btn-danger btn-rounded">Delete</button>
                                                        </form>    
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                           </table>  
                                           </table>  
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->

        
    </div><!-- /Page Inner -->

@endsection

@section('script')
<script src="{{asset('ui/backend/plugins/datatables/js/jquery.datatables.min.js')}}"></script>    
<script src="{{asset('ui/backend/js/pages/table-data.js')}}"></script>    
@endsection