routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ViewController@index')->name('view.home');
Route::get('/all/products','ViewController@allproducts')->name('view.allproducts');
Route::post('/search/products','ViewController@searchproducts')->name('view.searchproducts');
Route::get('/category/{id}','ViewController@sub_subcategoryproduct')->name('view.sub_subcategoryproduct');
Route::get('/manufacturer/{id}','ViewController@manufacturerproduct')->name('view.manufacturerproduct');
Route::post('/product/price/range','ViewController@sortbypricerange')->name('view.sortbypricerange');
Route::get('/product/sort/by/price/low','ViewController@sortbypricelow')->name('view.sortbypricelow');
Route::get('/product/sort/by/price/high','ViewController@sortbypricehigh')->name('view.sortbypricehigh');
Route::get('/product/sort/by/name','ViewController@sortbyname')->name('view.sortbyname');
Route::get('/product/cart/add/{id}','ViewController@addtocart')->name('view.addtocart');
Route::post('/product/cart/add','ViewController@addtocartwithquantity')->name('view.addtocart');
Route::delete('/product/cart/remove', 'ViewController@remove');
Route::get('/product/{id}', 'ViewController@viewproduct')->name('view.product');
Route::get('/product/category/{id}', 'ViewController@categoryproduct')->name('view.categoryproduct');
Route::get('/cart', 'ViewController@viewcart')->name('view.cart');
Route::patch('/cart/update', 'ViewController@cartupdate');

Route::get('/customer/login','ViewController@loginview')->name('view.loginview');
Route::post('/customer/login','ViewController@login')->name('view.login');
Route::post('/customer/register','ViewController@register')->name('view.register');
Route::get('/customer/logout','ViewController@logout_customer')->name('view.logout');

Route::group(['middleware' => ['checkcustomersession']], function () {
    Route::get('/checkout', 'ViewController@viewcheckout')->name('view.checkout');
    Route::post('/order', 'OrderController@store')->name('order.store');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin',function(){
        return view('backend.dashboard');
    })->name('admin.home');

    Route::resource('/manufacturers', 'ManufacturerController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/subcategories', 'SubcategoryController');
    Route::resource('/products', 'ProductController');
    Route::resource('/sub_subcategories', 'Sub_subcategoryController');
    Route::get('/find/subcategories/{id}', 'Sub_subcategoryController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/subcategories/{id}', 'ProductController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/sub_subcategories/{id}', 'ProductController@findsubsubcategories')->name('find.subsubcategories');

    Route::get('/products/order/manage','OrderController@manageOrder')->name('manage.order');
    Route::get('/products/order/view/{id}','OrderController@viewOrderDetail')->name('view.order');
    Route::get('/products/delete/order/{id}','OrderController@deleteOrder')->name('delete.order');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    protected $fillable = [
        'title','fontawsome','category_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }
    public function sub_subcategories()
    {
        return $this->hasMany(Sub_subcategory::class);
    }
}

app/Http/Controllers/SubcategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Subcategory;
use Session;
use Illuminate\Http\Request;

class SubcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories=Subcategory::all();

        return view('backend.subcategories.index',compact('subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();
        return view('backend.subcategories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->except('_token');

        Subcategory::create($data);
        Session::flash('message','Created successfully');
        return redirect(route('subcategories.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // dd($id);
        $categories=Category::all();
        $subcategory=Subcategory::findOrFail($id);

        return view('backend.subcategories.edit',compact('subcategory','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $subcategory=Subcategory::findOrfail($id);
        $data=$request->all();
        $subcategory->update($data);
        Session::flash('message','Updated successfully');
        return redirect(route('subcategories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategory=Subcategory::findOrfail($id);
        $subcategory->delete();
        Session::flash('message','Deleted successfully');
        return redirect(route('subcategories.index'));

    }
}

resources/views/backend/subcategories/create.blade.php
@extends('backend.layouts.master')


@section('content')
<div class="page-inner no-page-title">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-title">
                            Create subcategory
                        </div>    
                        <div class="panel-body">
                            <div class="row">
                                <center>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                    <form class="form-horizontal" action="{{ route('subcategories.store') }}" method="post">
                                    @csrf    
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Category</label>
                                                <div class="col-sm-10">
                                                 <select class="form-control form-select-options" name="category_id">
                                                    <option></option>
                                                    @foreach ($categories as $category)
                                                        <option value="{{ $category->id }}">{{ $category->title }}</option>
                                                    @endforeach
                                                 </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="title" id="inputEmail3" placeholder="Enter Subcategory Title ....">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Fontawsome</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="fontawsome" id="inputEmail3" placeholder="Enter Font Awsome Title .... example: fa-laptop">
                                                <p class="help-block help-block-p-text"></p>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success horizontal-form-button">Create</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-md-2"></div>
                                </center>
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->
    </div><!-- /Page Inner -->

@endsection

resources/views/backend/subcategories/edit.blade.php
@extends('backend.layouts.master')


@section('content')
<div class="page-inner no-page-title">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-title">
                            Update category
                        </div>    
                        <div class="panel-body">
                            <div class="row">
                                <center>
                                    <div class="col-md-2"></div>
                                    <div class="col-md-8">
                                    <form class="form-horizontal" action="{{ route('subcategories.update',$subcategory->id) }}" method="post">
                                    @csrf    
                                            <input name="_method" type="hidden" value="PUT">
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Category</label>
                                                <div class="col-sm-10">
                                                    <select class="form-control form-select-options" name="category_id">
                                                    @foreach ($categories as $category)
                                                        <option value="{{ $category->id }}" {{ ( $category->id == $subcategory->category_id) ? 'selected' : '' }}> {{ $category->title }} </option>
                                                    @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="title" id="inputEmail3" value="{{ $subcategory->title }}">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEmail3" class="col-sm-2 control-label">Fontawsome</label>
                                                <div class="col-sm-10">
                                                <input type="text" class="form-control" name="fontawsome" id="inputEmail3" value="{{ $subcategory->fontawsome }}">
                                                <p class="help-block help-block-p-text"></p>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-success horizontal-form-button">Update</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="col-md-2"></div>
                                </center>
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->
    </div><!-- /Page Inner -->

@endsection

resources/views/backend/subcategories/index.blade.php
@extends('backend.layouts.master')
@section('css')
    <link href="{{asset('ui/backend/plugins/datatables/css/jquery.datatables.min.css')}}" rel="stylesheet">
    <link href="{{asset('ui/backend/plugins/datatables/css/jquery.datatables_themeroller.css')}}" rel="stylesheet">
@endsection

@section('content')
<div class="page-inner">

        <div class="page-title">
            <h3 class="breadcrumb-header">Subcategories</h3>
        </div>
        <div id="main-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-body">
                            @if(Session::has('message'))
                            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                            @endif
                            <div class="table-responsive">
                                    <table id="example" class="display table table-data-width">
                                            <thead>
                                                <tr>
                                                    <th>Category</th>
                                                    <th>Title</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tfoot>
                                                <tr>
                                                    <th>Category</th>
                                                    <th>Title</th>
                                                    <th>Action</th>
                                                </tr>
                                            </tfoot>
                                            <tbody>
                                                @foreach ($subcategories as $subcategory)
                                                    <tr>
                                                        <td>{{ $subcategory->category->title }}</td>
                                                        <td>{{ $subcategory->title }}</td>
                                                        <td>
                                                        <form action="{{ route('subcategories.destroy',$subcategory->id) }}" method="POST"> 
                                                        @csrf
                                                        <a href="{{ route('subcategories.edit',$subcategory->id) }}" type="button" class="btn btn-info btn-rounded">Update</a>
                                                        <input name="_method" type="hidden" value="DELETE">
                                                            <button type="submit" class="btn btn-danger btn-rounded">Delete</button>
                                                        </form>    
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                           </table>  
                                           </table>  
                            </div>    
                        </div>    
                    </div>    
                </div>
            </div><!-- Row -->
        </div><!-- Main Wrapper -->

        
    </div><!-- /Page Inner -->

@endsection

@section('script')
<script src="{{asset('ui/backend/plugins/datatables/js/jquery.datatables.min.js')}}"></script>    
<script src="{{asset('ui/backend/js/pages/table-data.js')}}"></script>    
@endsection