routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ViewController@index')->name('view.home');
Route::get('/all/products','ViewController@allproducts')->name('view.allproducts');
Route::post('/search/products','ViewController@searchproducts')->name('view.searchproducts');
Route::get('/category/{id}','ViewController@sub_subcategoryproduct')->name('view.sub_subcategoryproduct');
Route::get('/manufacturer/{id}','ViewController@manufacturerproduct')->name('view.manufacturerproduct');
Route::post('/product/price/range','ViewController@sortbypricerange')->name('view.sortbypricerange');
Route::get('/product/sort/by/price/low','ViewController@sortbypricelow')->name('view.sortbypricelow');
Route::get('/product/sort/by/price/high','ViewController@sortbypricehigh')->name('view.sortbypricehigh');
Route::get('/product/sort/by/name','ViewController@sortbyname')->name('view.sortbyname');
Route::get('/product/cart/add/{id}','ViewController@addtocart')->name('view.addtocart');
Route::post('/product/cart/add','ViewController@addtocartwithquantity')->name('view.addtocart');
Route::delete('/product/cart/remove', 'ViewController@remove');
Route::get('/product/{id}', 'ViewController@viewproduct')->name('view.product');
Route::get('/product/category/{id}', 'ViewController@categoryproduct')->name('view.categoryproduct');
Route::get('/cart', 'ViewController@viewcart')->name('view.cart');
Route::patch('/cart/update', 'ViewController@cartupdate');

Route::get('/customer/login','ViewController@loginview')->name('view.loginview');
Route::post('/customer/login','ViewController@login')->name('view.login');
Route::post('/customer/register','ViewController@register')->name('view.register');
Route::get('/customer/logout','ViewController@logout_customer')->name('view.logout');

Route::group(['middleware' => ['checkcustomersession']], function () {
    Route::get('/checkout', 'ViewController@viewcheckout')->name('view.checkout');
    Route::post('/order', 'OrderController@store')->name('order.store');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin',function(){
        return view('backend.dashboard');
    })->name('admin.home');

    Route::resource('/manufacturers', 'ManufacturerController');
    Route::resource('/categories', 'CategoryController');
    Route::resource('/subcategories', 'SubcategoryController');
    Route::resource('/products', 'ProductController');
    Route::resource('/sub_subcategories', 'Sub_subcategoryController');
    Route::get('/find/subcategories/{id}', 'Sub_subcategoryController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/subcategories/{id}', 'ProductController@findsubcategories')->name('find.subcategories');
    Route::get('/find/product/sub_subcategories/{id}', 'ProductController@findsubsubcategories')->name('find.subsubcategories');

    Route::get('/products/order/manage','OrderController@manageOrder')->name('manage.order');
    Route::get('/products/order/view/{id}','OrderController@viewOrderDetail')->name('view.order');
    Route::get('/products/delete/order/{id}','OrderController@deleteOrder')->name('delete.order');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layouts/partials/header.blade.php
<!-- Page Header -->
<div class="page-header">
        <div class="search-form">
            <form action="#" method="GET">
                <div class="input-group">
                    <input type="text" name="search" class="form-control search-input" placeholder="Type something...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" id="close-search" type="button"><i class="icon-close"></i></button>
                    </span>
                </div>
            </form>
        </div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <div class="logo-sm">
                        <a href="javascript:void(0)" id="sidebar-toggle-button"><i class="fa fa-bars"></i></a>
                        <a class="logo-box" href="index.html"><span>metro</span></a>
                    </div>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <i class="fa fa-angle-down"></i>
                    </button>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
            
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="collapsed-sidebar-toggle-inv"><a href="javascript:void(0)" id="collapsed-sidebar-toggle-button"><i class="fa fa-bars"></i></a></li>
                        <li><a href="javascript:void(0)" id="toggle-fullscreen"><i class="fa fa-expand"></i></a></li>
                        <li><a href="javascript:void(0)" id="search-button"><i class="fa fa-search"></i></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {{-- <li><a href="javascript:void(0)" class="right-sidebar-toggle" data-sidebar-id="main-right-sidebar"><i class="fa fa-envelope"></i></a></li> --}}
                        {{-- <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell"></i></a>
                            <ul class="dropdown-menu dropdown-lg dropdown-content">
                                <li class="drop-title">Notifications<a href="#" class="drop-title-link"><i class="fa fa-angle-right"></i></a></li>
                                <li class="slimscroll dropdown-notifications">
                                    <ul class="list-unstyled dropdown-oc">
                                        <li>
                                            <a href="#"><span class="notification-badge bg-info"><i class="fa fa-at"></i></span>
                                                <span class="notification-info">
                                                    <span class="notification-info"><b>John Doe</b> mentioned you in a post "Update v1.5"</span>
                                                    <small class="notification-date">06:07</small>
                                                </span></a>
                                        </li>
                                        <li>
                                            <a href="#"><span class="notification-badge bg-danger"><i class="fa fa-bolt"></i></span>
                                                <span class="notification-info">
                                                    <span class="notification-info">4 new special offers from the apps you follow!</span>
                                                    <small class="notification-date">Yesterday</small>
                                                </span></a>
                                        </li>
                                        <li>
                                            <a href="#"><span class="notification-badge bg-success"><i class="fa fa-bullhorn"></i></span>
                                                <span class="notification-info">
                                                    <span class="notification-info">There is a meeting with <b>Ethan</b> in 15 minutes!</span>
                                                    <small class="notification-date">Yesterday</small>
                                                </span></a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li> --}}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{{asset('ui/backend/images/avatars/avatar1.png')}}" alt="" class="img-circle"></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Profile</a></li>
                                <li><a href="#">Calendar</a></li>
                                <li><a href="#"><span class="badge pull-right badge-info">64</span>Messages</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Account Settings</a></li>

                                <li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div><!-- /Page Header -->

resources/views/backend/layouts/partials/sidebar.blade.php
<!-- Page Sidebar -->
<div class="page-sidebar">
<a class="logo-box" href="{{ route('view.home') }}"><span>Flipmart</span><i class="icon-radio_button_unchecked" id="fixed-sidebar-toggle-button"></i>
            <i class="icon-close" id="sidebar-toggle-button-close"></i></a>
        <div class="page-sidebar-inner">
            <div class="page-sidebar-menu">
                <ul class="accordion-menu">
                    <li class="active-page">
                    <a href="{{ route('admin.home') }}">
                            <i class="menu-icon icon-home4"></i><span>Dashboard</span>
                        </a>
                    </li>
                    {{-- <li>
                        <a href="email.html">
                            <i class="menu-icon icon-inbox"></i><span>Email</span>
                        </a>
                    </li> --}}
                    <li>
                        <a href="javascript:void(0)">
                            <i class="menu-icon fa fa-cubes"></i><span>Category</span>
                            <i class="accordion-icon fa fa-angle-left"></i>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="{{ route('categories.create') }}">Create</a></li>
                            <li><a href="{{ route('categories.index') }}">Manage</a></li>      
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <i class="menu-icon fa fa-cubes"></i><span>Subcategory</span>
                            <i class="accordion-icon fa fa-angle-left"></i>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="{{ route('subcategories.create') }}">Create</a></li>
                            <li><a href="{{ route('subcategories.index') }}">Manage</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <i class="menu-icon fa fa-cubes"></i><span>Sub subcat</span>
                            <i class="accordion-icon fa fa-angle-left"></i>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="{{ route('sub_subcategories.create') }}">Create</a></li>
                            <li><a href="{{ route('sub_subcategories.index') }}">Manage</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <i class="menu-icon fa fa-industry"></i><span>Menufracturer</span>
                            <i class="accordion-icon fa fa-angle-left"></i>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="{{ route('manufacturers.create') }}">Create</a></li>
                            <li><a href="{{ route('manufacturers.index') }}">Manage</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0)">
                            <i class="menu-icon icon-dropbox"></i><span>Product</span>
                            <i class="accordion-icon fa fa-angle-left"></i>
                        </a>
                        <ul class="sub-menu">
                            <li><a href="{{ route('products.create') }}">Create</a></li>
                            <li><a href="{{ route('products.index') }}">Manage</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{ route('manage.order') }}">
                            <i class="menu-icon fa fa-file-archive-o"></i><span>Order</span>
                        </a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div><!-- /Page Sidebar -->